pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
        sh 'ls -lh'
        echo 'files checking'
      catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh '''
                        javac multi-stage-multi-agent/HelloWorld.java
                        java multi-stage-multi-agent/HelloWorld
                    '''
                }
                echo 'Back-end stage completed, moving to Front-end...'
            }  
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
